### ISSUE TITLE
This will break after React 16.4.0

### ISSUE THREAD

**Issue by gaearon** [zilverline/react-tap-event-plugin#121]
We renamed some of the internal top level types in https://github.com/facebook/react/pull/12629 so the plugin in its current form will break. It's not a semver-major change because this plugin was never supported officially and relies on private APIs that can change in any patch.

**Comment by s0meone** [comment]
Hi @gaearon, thanks for letting us know. You've already warned for this in #112 so we knew this was coming. We're not planning on supporting >=16.4 and will make this clear in the README. I think it's time to move away from this plugin anyway since the problem [has gone away mostly](https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away).

**Comment by gaearon** [comment]
Lol I forgot about that issue, sorry for the spam. Feel free to close :-)

**Comment by s0meone** [comment]
No worries, thanks for the reminder 😄 

You [suggested](https://github.com/facebook/react/issues/11689) turning this plugin into a `<Tappable>` component but I feel that would create a bigger migration path than simply replacing `onTouchTap` to `onClick`. Since the problem is already solved by most browsers.

I've already [experimented](https://github.com/zilverline/react-tap-event-plugin/tree/refactor-plugin-hoc) with a userland `onTouchTap` replacement but performance was very poor. The main problem is the name of the handler on the lower case React elements (`div`, `button` etc), this has to be replaced with the actual handler before rendering.

So I think it's time to end this plugin.

**Comment by konglx90** [comment]
Everything will come to an end. Anyway, it works good on my app. Thank you very much!

**Comment by pacifio** [comment]
I am using react 16.0.0 on an old project but it wont work ...
