### ISSUE TITLE
React 0.13.x obviates need for plugin?

### ISSUE THREAD

**Issue by py-in-the-sky** [zilverline/react-tap-event-plugin#17]
I have upgraded my app to React 0.13.1 and have tested out removing this plugin altogether and changing `onTouchTap` back to React's `onClick`.  It seems that React's `onClick` now handles taps in iOS.  Does React 0.13.x remove the need for this plugin, or are there cases that you know of where this plugin is still needed?

Thank you for the plugin!

**Comment by iamstarkov** [comment]
not sure if it about react, suggesting that you were testing in some browsers, which handle 300ms delay by itself

**Comment by py-in-the-sky** [comment]
Good point!  I'll test on a larger sample of browsers.

**Comment by spicydonuts** [comment]
Just saw this and gave it a try.  I still have the 300ms delay on iOS Safari without `react-tap-event-plugin`.  Currently on React `0.13.2`.

**Comment by tomhicks-bsf** [comment]
React has always had onClicks "working" for touch events, because that's not part of React, it's part of the browser's built-in behaviour. This plugin exists to remove the annoying but kinda necessary 300ms delay that Mobile Safari (and other browsers) implement on taps.

It does this by listening for touch events and on touchend (if it considers it appropriate) triggering an onTouchTap event. It also responds to clicks in the traditional sense, and has logic to try to remove taps and clicks both being fired on touch devices.

**Comment by s0meone** [comment]
React did merge the same fix in their `TapEventPlugin` but they didn't release it yet. It's on the roadmap for 1.0. And yes, the issue is still there, since it's a browser problem not a React problem.
