### ISSUE TITLE
v1.0.0 breaks some of Material-UI

### ISSUE THREAD

**Issue by prescottprue** [zilverline/react-tap-event-plugin#68]
Version `v1.0.0` breaks a few things within Material-UI  have I have noticed so far:

* IconMenu no longer opens
* Buttons `onTouchTap` attribute no longer works, and `onClick` must be used

Maybe I there is some config I am missing?

My solution so far has been to stick to using `v0.2.1`, which does not have any of these issues. Not sure what advantages I am missing out on by not going `v1.0.0`. Is there a CHANGELOG file floating around?

**Comment by madjam002** [comment]
v1.0.0 is only for React 15 users. If you're still on v0.14 you'll need to stay on an older version.

**Comment by jakeboone02** [comment]
Can the maintainer put a note in the README about this?  Add instructions for installing the version that works with `react@<15`, probably like this: `npm i --save react-tap-event-plugin@0.2.2`.  Otherwise everyone that installs the latest of this plugin and hasn't upgraded to React 15 yet will have the same issues.

**Comment by madjam002** [comment]
Done

**Comment by jakeboone02** [comment]
Thanks, @madjam002!
